/**
 * PICNIX project
 * 
 * intrp.h
 * 
 * PIC18F4550 interruption regs
 */
 
#ifndef __PICNIX_INTRP_H
#define __PICNIX_INTRP_H 1

// inline assembly compatible bit definitions
#define INT_RBIF	_INTCON, 0
#define INT_RBIE	_INTCON, 3
#define INT_RBIP	_INTCON2, 0

#define INT_INT0IF	_INTCON, 1
#define INT_INT0IE	_INTCON, 4
//#define INT_INT0IP not selectable, always?

#define INT_TMR0IF	_INTCON, 2
#define INT_TMR0IE	_INTCON, 5
#define INT_TMR0IP	_INTCON2, 2

#define INT_INT1IF	_INTCON3, 0
#define INT_INT1IE	_INTCON3, 3
#define INT_INT1IP	_INTCON3, 6

#define INT_INT2IF	_INTCON3, 1
#define INT_INT2IE	_INTCON3, 4
#define INT_INT2IP	_INTCON3, 7

// device dependent
#define INT_TMR1IDX	0
#define INT_TMR1SUF	1
#define INT_TMR2IDX	1
#define INT_TMR2SUF	1
#define INT_CCP1IDX	2
#define INT_CCP1SUF	1
#define INT_SSPIDX	3
#define INT_SSPSUF	1
#define INT_TXIDX	4
#define INT_TXSUF	1
#define INT_RCIDX	5
#define INT_RCSUF	1
#define INT_ADIDX	6
#define INT_ADSUF	1
#define INT_PSPIDX	7
#define INT_PSPSUF	1

#define INT_CCP2IDX	0
#define INT_CCP2SUF	2
#define INT_TMR3IDX	1
#define INT_TMR3SUF	2
#define INT_LVDIDX	2
#define INT_LVDSUF	2
#define INT_BCOLIDX	3
#define INT_BCOLSUF	2
#define INT_EEIDX	4
#define INT_EESUF	2
#define INT_USBIDX	5
#define INT_USBSUF	2

// device independent
#define INT_PIR(suf)	__concat(_PIR, suf)
#define INT_PIE(suf)	__concat(_PIE, suf)
#define INT_IPR(suf)	__concat(_IPR, suf)

#define INT_TMR1IF	INT_PIR(INT_TMR1SUF), INT_TMR1IDX
#define INT_TMR1IE	INT_PIE(INT_TMR1SUF), INT_TMR1IDX
#define INT_TMR1IP	INT_IPR(INT_TMR1SUF), INT_TMR1IDX

#define INT_TMR2IF	INT_PIR(INT_TMR2SUF), INT_TMR2IDX
#define INT_TMR2IE	INT_PIE(INT_TMR2SUF), INT_TMR2IDX
#define INT_TMR2IP	INT_IPR(INT_TMR2SUF), INT_TMR2IDX

#define INT_CCP1IF	INT_PIR(INT_CCP1SUF), INT_CCP1IDX
#define INT_CCP1IE	INT_PIE(INT_CCP1SUF), INT_CCP1IDX
#define INT_CCP1IP	INT_IPR(INT_CCP1SUF), INT_CCP1IDX

#define INT_SSPIF	INT_PIR(INT_SSPSUF), INT_SSPIDX
#define INT_SSPIE	INT_PIE(INT_SSPSUF), INT_SSPIDX
#define INT_SSPIP	INT_IPR(INT_SSPSUF), INT_SSPIDX

#define INT_MSSPIF	INT_SSPIF
#define INT_MSSPIE	INT_SSPIE
#define INT_MSSPIP	INT_SSPIP

#define INT_TXIF	INT_PIR(INT_TXSUF), INT_TXIDX
#define INT_TXIE	INT_PIE(INT_TXSUF), INT_TXIDX
#define INT_TXIP	INT_IPR(INT_TXSUF), INT_TXIDX

#define INT_RCIF	INT_PIR(INT_RCSUF), INT_RCIDX
#define INT_RCIE	INT_PIE(INT_RCSUF), INT_RCIDX
#define INT_RCIP	INT_IPR(INT_RCSUF), INT_RCIDX

#define INT_ADIF	INT_PIR(INT_ADSUF), INT_ADIDX
#define INT_ADIE	INT_PIE(INT_ADSUF), INT_ADIDX
#define INT_ADIP	INT_IPR(INT_ADSUF), INT_ADIDX

#define INT_PSPIF	INT_PIR(INT_PSPSUF), INT_PSPIDX
#define INT_PSPIE	INT_PIE(INT_PSPSUF), INT_PSPIDX
#define INT_PSPIP	INT_IPR(INT_PSPSUF), INT_PSPIDX

#define INT_CCP2IF	INT_PIR(INT_CCP2SUF), INT_CCP2IDX
#define INT_CCP2IE	INT_PIE(INT_CCP2SUF), INT_CCP2IDX
#define INT_CCP2IP	INT_IPR(INT_CCP2SUF), INT_CCP2IDX

#define INT_TMR3IF	INT_PIR(INT_TMR3SUF), INT_TMR3IDX
#define INT_TMR3IE	INT_PIE(INT_TMR3SUF), INT_TMR3IDX
#define INT_TMR3IP	INT_IPR(INT_TMR3SUF), INT_TMR3IDX

#define INT_LVDIF	INT_PIR(INT_LVDSUF), INT_LVDIDX
#define INT_LVDIE	INT_PIE(INT_LVDSUF), INT_LVDIDX
#define INT_LVDIP	INT_IPR(INT_LVDSUF), INT_LVDIDX

#define INT_BCOLIF	INT_PIR(INT_BCOLSUF), INT_BCOLIDX
#define INT_BCOLIE	INT_PIE(INT_BCOLSUF), INT_BCOLIDX
#define INT_BCOLIP	INT_IPR(INT_BCOLSUF), INT_BCOLIDX

#define INT_EEIF	INT_PIR(INT_EESUF), INT_EEIDX
#define INT_EEIE	INT_PIE(INT_EESUF), INT_EEIDX
#define INT_EEIP	INT_IPR(INT_EESUF), INT_EEIDX

#define INT_USBIF	INT_PIR(INT_USBSUF), INT_USBIDX
#define INT_USBIE	INT_PIE(INT_USBSUF), INT_USBIDX
#define INT_USBIP	INT_IPR(INT_USBSUF), INT_USBIDX

// interrupt arguments
#define INT_RB		INT_RBIF
#define INT_INT0	INT_INT0IF
#define INT_INT1	INT_INT1IF
#define INT_INT2	INT_INT2IF
#define INT_CCP1	INT_CCP1IF
#define INT_CCP2	INT_CCP2IF
#define INT_TMR0	INT_TMR0IF
#define INT_TMR1	INT_TMR1IF
#define INT_TMR2	INT_TMR2IF
#define INT_TMR3	INT_TMR3IF
#define INT_EE		INT_EEIF
#define INT_BCOL	INT_BCOLIF
#define INT_LVD		INT_LVDIF
#define INT_PSP		INT_PSPIF
#define INT_AD		INT_ADIF
#define INT_RC		INT_RCIF
#define INT_TX		INT_TXIF
#define INT_SSP		INT_SSPIF
#define INT_MSSP	INT_SSPIF
#define INT_USB		INT_USBIF

#endif // __PICNIX_INTRP_H
